/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：test.NewsStoryscript.java
 * 日 期：Thu Jul 18 10:35:00 CST 2013
 */
package test;

import java.io.Serializable;
import java.sql.Timestamp;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "NEWS_STORYSCRIPT", keyGenerator = "select")
public class NewsStoryscript implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CLIP_ID = "CLIP_ID";
	public static String PROP_CONTENT = "CONTENT";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_DURATION = "DURATION";
	public static String PROP_EXTRA_INFO = "EXTRA_INFO";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_2 = "FIELD_2";
	public static String PROP_FIELD_3 = "FIELD_3";
	public static String PROP_PLAY_TYPE = "PLAY_TYPE";
	public static String PROP_POSITION = "POSITION";
	public static String PROP_SCRIPT_ID = "SCRIPT_ID";
	public static String PROP_SCRIPT_TYPE = "SCRIPT_TYPE";
	public static String PROP_START_POINT = "START_POINT";
	public static String PROP_STORY_ID = "STORY_ID";
	
	//primary key field of scriptId
	@FieldMapping(columnName = "SCRIPT_ID", columnType = 2, primary = true)
	private Long scriptId;
	@FieldMapping(columnName = "CLIP_ID", columnType = 2)
	private Integer clipId;
	@FieldMapping(columnName = "CONTENT", columnType = 2005)
	private String content;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Timestamp createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 2)
	private Integer createUserid;
	@FieldMapping(columnName = "DURATION", columnType = 2)
	private Integer duration;
	@FieldMapping(columnName = "EXTRA_INFO", columnType = 12)
	private String extraInfo;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "FIELD_3", columnType = 12)
	private String field3;
	@FieldMapping(columnName = "PLAY_TYPE", columnType = 2)
	private Integer playType;
	@FieldMapping(columnName = "POSITION", columnType = 2)
	private Integer position;
	@FieldMapping(columnName = "SCRIPT_TYPE", columnType = 12)
	private String scriptType;
	@FieldMapping(columnName = "START_POINT", columnType = 2)
	private Integer startPoint;
	@FieldMapping(columnName = "STORY_ID", columnType = 2)
	private Integer storyId;
	
	public NewsStoryscript() {
		super();
	}

	public NewsStoryscript(Long scriptId) {
		this.scriptId = scriptId;
	}

	public NewsStoryscript(String content, Timestamp createTime, Integer createUserid, Integer duration, Integer playType, Integer position, String scriptType, Integer storyId) {
		this.content = content;
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.duration = duration;
		this.playType = playType;
		this.position = position;
		this.scriptType = scriptType;
		this.storyId = storyId;
	}

	/**
	 * @return the clipId
	 */
	public Integer getClipId() {
		return this.clipId;
	}
	
	/**
	 * @param clipId the clipId to set
	 */
	public void setClipId(Integer value) {
		this.clipId = value;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return this.content;
	}
	
	/**
	 * @param content the content to set
	 */
	public void setContent(String value) {
		this.content = value;
	}

	/**
	 * @return the createTime
	 */
	public Timestamp getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Timestamp value) {
		this.createTime = value;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String value) {
		this.createUser = value;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer value) {
		this.createUserid = value;
	}

	/**
	 * @return the duration
	 */
	public Integer getDuration() {
		return this.duration;
	}
	
	/**
	 * @param duration the duration to set
	 */
	public void setDuration(Integer value) {
		this.duration = value;
	}

	/**
	 * @return the extraInfo
	 */
	public String getExtraInfo() {
		return this.extraInfo;
	}
	
	/**
	 * @param extraInfo the extraInfo to set
	 */
	public void setExtraInfo(String value) {
		this.extraInfo = value;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String value) {
		this.field1 = value;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String value) {
		this.field2 = value;
	}

	/**
	 * @return the field3
	 */
	public String getField3() {
		return this.field3;
	}
	
	/**
	 * @param field3 the field3 to set
	 */
	public void setField3(String value) {
		this.field3 = value;
	}

	/**
	 * @return the playType
	 */
	public Integer getPlayType() {
		return this.playType;
	}
	
	/**
	 * @param playType the playType to set
	 */
	public void setPlayType(Integer value) {
		this.playType = value;
	}

	/**
	 * @return the position
	 */
	public Integer getPosition() {
		return this.position;
	}
	
	/**
	 * @param position the position to set
	 */
	public void setPosition(Integer value) {
		this.position = value;
	}

	/**
	 * @return the scriptId
	 */
	public Long getScriptId() {
		return this.scriptId;
	}
	
	/**
	 * @param scriptId the scriptId to set
	 */
	public void setScriptId(Long value) {
		this.scriptId = value;
	}

	/**
	 * @return the scriptType
	 */
	public String getScriptType() {
		return this.scriptType;
	}
	
	/**
	 * @param scriptType the scriptType to set
	 */
	public void setScriptType(String value) {
		this.scriptType = value;
	}

	/**
	 * @return the startPoint
	 */
	public Integer getStartPoint() {
		return this.startPoint;
	}
	
	/**
	 * @param startPoint the startPoint to set
	 */
	public void setStartPoint(Integer value) {
		this.startPoint = value;
	}

	/**
	 * @return the storyId
	 */
	public Integer getStoryId() {
		return this.storyId;
	}
	
	/**
	 * @param storyId the storyId to set
	 */
	public void setStoryId(Integer value) {
		this.storyId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof NewsStoryscript)) {
			return false;
		}
		NewsStoryscript other = (NewsStoryscript)o;
		if (null == this.scriptId) {
			if (other.scriptId != null)
				return false;
		} else if (!this.scriptId.equals(other.scriptId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((scriptId == null) ? 0 : scriptId.hashCode());
		return result;
	}
	
}