/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：test.NewsStoryclip.java
 * 日 期：Fri May 24 16:44:06 CST 2013
 */
package test;

import java.io.Serializable;
import java.sql.Timestamp;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "NEWS_STORYCLIP", keyGenerator = "native")
public class NewsStoryclip implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CLIP_ID = "clipId";
	public static String PROP_CLIP_NAME = "clipName";
	public static String PROP_CLIP_TYPE = "clipType";
	public static String PROP_CLIP_UID = "clipUid";
	public static String PROP_CREATE_TIME = "createTime";
	public static String PROP_CREATE_USER = "createUser";
	public static String PROP_CREATE_USERID = "createUserid";
	public static String PROP_DURATION = "duration";
	public static String PROP_FIELD_1 = "field1";
	public static String PROP_FIELD_2 = "field2";
	public static String PROP_FIELD_3 = "field3";
	public static String PROP_ICON_FILE = "iconFile";
	public static String PROP_ICON_PATH = "iconPath";
	public static String PROP_STORY_ID = "storyId";
	
	//primary key field of clipId
	@FieldMapping(columnName = "CLIP_ID", columnType = 2, primary = true)
	private Long clipId;
	@FieldMapping(columnName = "CLIP_NAME", columnType = 12)
	private String clipName;
	@FieldMapping(columnName = "CLIP_TYPE", columnType = 2)
	private Integer clipType;
	@FieldMapping(columnName = "CLIP_UID", columnType = 12)
	private String clipUid;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Timestamp createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 2)
	private Integer createUserid;
	@FieldMapping(columnName = "DURATION", columnType = 2)
	private Integer duration;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "FIELD_3", columnType = 12)
	private String field3;
	@FieldMapping(columnName = "ICON_FILE", columnType = 2005)
	private byte[] iconFile;
	@FieldMapping(columnName = "ICON_PATH", columnType = 12)
	private String iconPath;
	@FieldMapping(columnName = "STORY_ID", columnType = 2)
	private Integer storyId;
	
	public NewsStoryclip() {
		super();
	}

	public NewsStoryclip(Long clipId) {
		this.clipId = clipId;
	}

	public NewsStoryclip(Integer clipType, String clipUid, Timestamp createTime, Integer createUserid, Integer duration, Integer storyId) {
		this.clipType = clipType;
		this.clipUid = clipUid;
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.duration = duration;
		this.storyId = storyId;
	}

	/**
	 * @return the clipId
	 */
	public Long getClipId() {
		return this.clipId;
	}
	
	/**
	 * @param clipId the clipId to set
	 */
	public void setClipId(Long value) {
		this.clipId = value;
	}

	/**
	 * @return the clipName
	 */
	public String getClipName() {
		return this.clipName;
	}
	
	/**
	 * @param clipName the clipName to set
	 */
	public void setClipName(String value) {
		this.clipName = value;
	}

	/**
	 * @return the clipType
	 */
	public Integer getClipType() {
		return this.clipType;
	}
	
	/**
	 * @param clipType the clipType to set
	 */
	public void setClipType(Integer value) {
		this.clipType = value;
	}

	/**
	 * @return the clipUid
	 */
	public String getClipUid() {
		return this.clipUid;
	}
	
	/**
	 * @param clipUid the clipUid to set
	 */
	public void setClipUid(String value) {
		this.clipUid = value;
	}

	/**
	 * @return the createTime
	 */
	public Timestamp getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Timestamp value) {
		this.createTime = value;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String value) {
		this.createUser = value;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer value) {
		this.createUserid = value;
	}

	/**
	 * @return the duration
	 */
	public Integer getDuration() {
		return this.duration;
	}
	
	/**
	 * @param duration the duration to set
	 */
	public void setDuration(Integer value) {
		this.duration = value;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String value) {
		this.field1 = value;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String value) {
		this.field2 = value;
	}

	/**
	 * @return the field3
	 */
	public String getField3() {
		return this.field3;
	}
	
	/**
	 * @param field3 the field3 to set
	 */
	public void setField3(String value) {
		this.field3 = value;
	}

	/**
	 * @return the iconFile
	 */
	public byte[] getIconFile() {
		return this.iconFile;
	}
	
	/**
	 * @param iconFile the iconFile to set
	 */
	public void setIconFile(byte[] value) {
		this.iconFile = value;
	}

	/**
	 * @return the iconPath
	 */
	public String getIconPath() {
		return this.iconPath;
	}
	
	/**
	 * @param iconPath the iconPath to set
	 */
	public void setIconPath(String value) {
		this.iconPath = value;
	}

	/**
	 * @return the storyId
	 */
	public Integer getStoryId() {
		return this.storyId;
	}
	
	/**
	 * @param storyId the storyId to set
	 */
	public void setStoryId(Integer value) {
		this.storyId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof NewsStoryclip)) {
			return false;
		}
		NewsStoryclip other = (NewsStoryclip)o;
		if (null == this.clipId) {
			if (other.clipId != null)
				return false;
		} else if (!this.clipId.equals(other.clipId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((clipId == null) ? 0 : clipId.hashCode());
		return result;
	}
	
}